name: $(Build.SourceBranchName) $(Date:yyyy-MM-dd).$(BuildID)

trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "v*"

pr:
  - "*"

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  tagBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  releaseBranchBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]
  prBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/pull/')]

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Bash@3
            displayName: Find release version
            condition: eq(variables.tagBuild, 'true')
            inputs:
              targetType: 'inline'
              script: |
                echo "##vso[task.setvariable variable=version]`grep -o -P '(?<=version\>).*(?=-SNAPSHOT)' pom.xml | head -n 1`"
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'bjoggis-studios-only, bjoggis-studios-releases'
          - task: Cache@2
            inputs:
              key: 'maven|v1'
              path: '$(MAVEN_CACHE_FOLDER)'
            displayName: Cache Maven local repo
          - task: Maven@3
            displayName: Prepare Release
            condition: eq(variables.tagBuild, 'true')
            inputs:
              mavenPomFile: pom.xml
              goals: versions:set -DnewVersion=$(VERSION) -DgenerateBackupPoms=false --no-transfer-progress
              options: $(MAVEN_OPTS)
              skipEffectivePom: true
              publishJUnitResults: false
          - task: Maven@3
            displayName: mvn clean verify
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean verify -T4 --no-transfer-progress'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              mavenVersionOption: 'Default'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              mavenAuthenticateFeed: false
              effectivePomSkip: true
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
          - task: Maven@3
            displayName: mvn package
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              effectivePomSkip: true
              publishJUnitResults: false
              goals: '-DskipTests package --no-transfer-progress'
          - task: Maven@3
            displayName: mvn deploy
            condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables.tagBuild, 'true'), eq(variables.releaseBranchBuild, 'true'), eq(variables.prBuild, 'true')))
            inputs:
              mavenPomFile: 'pom.xml'
              goals: '-DskipTests -Prpmbuilder deploy --no-transfer-progress'
              mavenOptions: '$(MAVEN_OPTS)'
              skipEffectivePom: true
              publishJUnitResults: false
          - task: Maven@3
            displayName: Docker Build
            inputs:
              mavenPomFile: 'pom.xml'
              goals: '-DskipTests docker:build'
              mavenOptions: '$(MAVEN_OPTS)'
              skipEffectivePom: true
              publishJUnitResults: false
          - task: Bash@3
            displayName: Docker Authenticate
            env:
              DOCKER_PASSWORD: $(docker-password)
            inputs:
              targetType: 'inline'
              script: |
                docker login -u $(docker-username) -p $DOCKER_PASSWORD
          - task: Maven@3
            displayName: Docker Push
            inputs:
              mavenPomFile: 'pom.xml'
              goals: '-DskipTests docker:push'
              mavenOptions: '$(MAVEN_OPTS)'
              skipEffectivePom: true
              publishJUnitResults: false