# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Cache@2
            displayName: Cache Maven local repo
            inputs:
                key: 'maven | "$(Agent.OS)" | **/pom.xml'
                restoreKeys: |
                  maven | "$(Agent.OS)"
                  maven
                path: $(MAVEN_CACHE_FOLDER)
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'bjoggis-studios-maven'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean test deploy'
              options: '-T 4'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              mavenVersionOption: 'Default'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              mavenAuthenticateFeed: true
              effectivePomSkip: true
              sonarQubeRunAnalysis: false
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'Pay-As-You-Go(5b21c31b-9aa7-41ed-9b15-42992ae6edf7)'
              azureContainerRegistry: '{"loginServer":"bjoggisacr.azurecr.io", "id" : "/subscriptions/5b21c31b-9aa7-41ed-9b15-42992ae6edf7/resourceGroups/cloud-shell-storage-westeurope/providers/Microsoft.ContainerRegistry/registries/bjoggisacr"}'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Build services'
              includeSourceTags: true
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'Pay-As-You-Go(5b21c31b-9aa7-41ed-9b15-42992ae6edf7)'
              azureContainerRegistry: '{"loginServer":"bjoggisacr.azurecr.io", "id" : "/subscriptions/5b21c31b-9aa7-41ed-9b15-42992ae6edf7/resourceGroups/cloud-shell-storage-westeurope/providers/Microsoft.ContainerRegistry/registries/bjoggisacr"}'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Push services'
              includeSourceTags: true
          - task: SSH@0
            inputs:
              sshEndpoint: 'Bjoggis01'
              runOptions: 'commands'
              commands: |
                docker stop config-server || true
                docker rm config-server || true
                docker run -d --pull always --name config-server -p 8888:8888 bjoggisacr.azurecr.io/config-server || true
              failOnStdErr: false
              readyTimeout: '20000'